# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * account_plaid
# 
# Translators:
# Eric Geens <ericgeens@yahoo.com>, 2015
# Yenthe Van Ginneken <yenthespam@gmail.com>, 2015
msgid ""
msgstr ""
"Project-Id-Version: Odoo 9.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-10-01 06:30+0000\n"
"PO-Revision-Date: 2015-09-21 14:38+0000\n"
"Last-Translator: Yenthe Van Ginneken <yenthespam@gmail.com>\n"
"Language-Team: Dutch (http://www.transifex.com/odoo/odoo-9/language/nl/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: nl\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_online_account_token
msgid "Access Token"
msgstr "Toegangstoken"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:52
#: code:addons/account_plaid/models/plaid.py:63
#, python-format
msgid "An error has occurred while trying to connect to plaid service"
msgstr "Er is een fout opgetreden bij de verbinding naar de plaid.com dienst"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_online_account
msgid "Email Thread"
msgstr "E-mail discussie"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:129
#, python-format
msgid "Error in synchronization"
msgstr "Synchronisatiefout"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:136
#, python-format
msgid "Error with Plaid.com"
msgstr "Fout bij plaid.com"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_account_journal
msgid "Journal"
msgstr "Dagboek"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_account_journal_onlinesync_config_plaid_account_id
msgid "Online Account"
msgstr "Online rekening"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_online_account_plaid_id
msgid "Plaid Account"
msgstr "Plaid account"

#. module: account_plaid
#: model:ir.ui.view,arch_db:account_plaid.account_config_settings_view_inherit_plaid
msgid "Plaid Configuration"
msgstr "Plaid configuratie"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_account_config_settings_plaid_id
msgid "Plaid ID"
msgstr "Plaid ID"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_account_config_settings_plaid_secret
msgid "Plaid Secret"
msgstr "Plaid Secret"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:130
#, python-format
msgid ""
"The synchronization of the journal %s with the plaid account %s has "
"failed.<br>The error message is :<br>%s"
msgstr "De synchronisatie tussen dagboek %s en de plaid account %s is mislukt.<br> Foutmelding :<br>%s"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:137
#, python-format
msgid ""
"The synchronization with Plaid.com failed. Please check the error : <br> %s"
msgstr "De synchronisatie met plaid.com is mislukt. Controleer foutmelding : <br> %s"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:38
#, python-format
msgid ""
"You haven't configure your plaid account, please go to accounting/settings "
"to configure it"
msgstr "U hebt uw plaid account nog niet ingesteld; ga naar boekhouding/instellingen om hem in te stellen"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_account_config_settings
msgid "account.config.settings"
msgstr "account.config.settings"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_account_journal_onlinesync_config
msgid "account.journal.onlinesync.config"
msgstr "account.journal.onlinesync.config"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_online_institution
msgid "online.institution"
msgstr "online.institution"
